name: Publish

on:
  push:
    branches: [master]

jobs:
  publish-test:
    uses: ./.github/workflows/pull-request.yml

  publish-npm:
    name: NPM
    needs: [publish-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: NPM
        run: npm ci

      - name: Build
        run: npm run build

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
