name: Pull Request

on:
  pull_request:

  workflow_call:
    inputs:
      build:
        description: Should it test by building?
        required: false
        default: true
        type: boolean

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
